# 足够内存给 MC 反编译
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
# 国内网络下载 Fabric 等大文件需加大超时
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.org.gradle.internal.http.connectionTimeout=180000

## Environment Properties
minecraft_version=1.20.1
loader_version=0.15.11
fabric_version=0.92.11+1.20.1
cloth_version=11.1.136
modmenu_version=7.1.0

## Mod Properties
mod_id=chuying
mod_name=\u8f66\u4e07\u5973\u4ec6:\u891a\u5b34\u4ee3\u6253
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=com.chuying
mod_authors=xiaoou6630
mod_description=\u891a\u5b34\u4ee3\u6253\uff08Chuying Proxy Play\uff09\uff1a\u4e3a Touhou Little Maid \u7684\u68cb\u7c7b\uff08\u4e94\u5b50\u68cb/\u4e2d\u56fd\u8c61\u68cb/\u56fd\u9645\u8c61\u68cb\uff09\u63a5\u5165\u5916\u90e8\u5f3a\u5f15\u64ce\u81ea\u52a8\u843d\u5b50\u3002\u7eaf\u5ba2\u6237\u7aef\uff0c\u670d\u52a1\u5668\u514d\u88c5\u3002
